**ASSIGNMENT -2 AIAC**
NAME: B.VYSHNAVI
HALL TNO- 2303A51884
BATCH-02

Here's a Python function that takes a list of numbers as input and returns their mean, minimum, and maximum values. It uses the `statistics` module for the mean calculation and built-in `min()` and `max()` functions.

In [1]:
import statistics

def calculate_summary_statistics(numbers_list):
    """
    Calculates the mean, minimum, and maximum values from a list of numbers.

    Args:
        numbers_list (list): A list of numerical values.

    Returns:
        tuple: A tuple containing (mean, minimum, maximum).
               Returns (None, None, None) if the list is empty.
    """
    if not numbers_list:
        return None, None, None

    mean_value = statistics.mean(numbers_list)
    min_value = min(numbers_list)
    max_value = max(numbers_list)

    return mean_value, min_value, max_value

# Example usage:
survey_data = [10, 15, 20, 25, 30, 12, 18, 22, 28, 35]
mean, minimum, maximum = calculate_summary_statistics(survey_data)

print(f"Survey Data: {survey_data}")
print(f"Mean: {mean}")
print(f"Minimum: {minimum}")
print(f"Maximum: {maximum}")

# Example with an empty list
empty_data = []
mean_empty, min_empty, max_empty = calculate_summary_statistics(empty_data)
print(f"\nEmpty Data: {empty_data}")
print(f"Mean: {mean_empty}")
print(f"Minimum: {min_empty}")
print(f"Maximum: {max_empty}")

Survey Data: [10, 15, 20, 25, 30, 12, 18, 22, 28, 35]
Mean: 21.5
Minimum: 10
Maximum: 35

Empty Data: []
Mean: None
Minimum: None
Maximum: None


# Task
Generate a Python function to check if a number is an Armstrong number and provide an explanation of its logic.

## Generate Armstrong Number Checker (Gemini)

### Subtask:
Generate a Python function to check if a number is an Armstrong number.


**Reasoning**:
I need to generate a Python function named `is_armstrong_number` that checks if a given number is an Armstrong number, following the detailed instructions provided by the user. I will also include example usage to demonstrate its functionality.



In [3]:
def is_armstrong_number(number):
    """
    Checks if a given number is an Armstrong number.

    An Armstrong number (or narcissistic number) is a number that is the sum
    of its own digits each raised to the power of the number of digits.

    Args:
        number (int): The integer to check.

    Returns:
        bool: True if the number is an Armstrong number, False otherwise.
    """
    if not isinstance(number, int) or number < 0:
        return False

    num_str = str(number)
    num_digits = len(num_str)
    sum_of_powers = 0

    for digit_char in num_str:
        digit = int(digit_char)
        sum_of_powers += digit ** num_digits

    return sum_of_powers == number

# Example usage:
print(f"Is 9 an Armstrong number? {is_armstrong_number(9)}")        # Expected: True (9^1 = 9)
print(f"Is 10 an Armstrong number? {is_armstrong_number(10)}")      # Expected: False (1^2 + 0^2 = 1)
print(f"Is 153 an Armstrong number? {is_armstrong_number(153)}")    # Expected: True (1^3 + 5^3 + 3^3 = 1 + 125 + 27 = 153)
print(f"Is 370 an Armstrong number? {is_armstrong_number(370)}")    # Expected: True (3^3 + 7^3 + 0^3 = 27 + 343 + 0 = 370)
print(f"Is 371 an Armstrong number? {is_armstrong_number(371)}")    # Expected: True (3^3 + 7^3 + 1^3 = 27 + 343 + 1 = 371)
print(f"Is 1634 an Armstrong number? {is_armstrong_number(1634)}")  # Expected: True (1^4 + 6^4 + 3^4 + 4^4 = 1 + 1296 + 81 + 256 = 1634)
print(f"Is 1000 an Armstrong number? {is_armstrong_number(1000)}") # Expected: False (1^4 + 0^4 + 0^4 + 0^4 = 1)
print(f"Is -153 an Armstrong number? {is_armstrong_number(-153)}") # Expected: False (negative numbers are not Armstrong numbers)


Is 9 an Armstrong number? True
Is 10 an Armstrong number? False
Is 153 an Armstrong number? True
Is 370 an Armstrong number? True
Is 371 an Armstrong number? True
Is 1634 an Armstrong number? True
Is 1000 an Armstrong number? False
Is -153 an Armstrong number? False


### Explanation of `is_armstrong_number` function logic:

The `is_armstrong_number` function determines if a given integer is an Armstrong number. An Armstrong number is a number that is equal to the sum of its own digits, each raised to the power of the total number of digits in the number.

Here's a breakdown of the function's logic:

1.  **Input Validation**: The function first checks if the input `number` is an integer and if it's non-negative. Armstrong numbers are typically defined for positive integers. If the number is not an integer or is negative, it immediately returns `False`.

2.  **Convert to String and Count Digits**: The `number` is converted to a string (`num_str`). This allows easy iteration over its digits and also helps in determining the `num_digits` (length of the string).

3.  **Initialize Sum**: A variable `sum_of_powers` is initialized to `0`. This variable will accumulate the sum of each digit raised to the power of `num_digits`.

4.  **Iterate and Calculate Powers**: The function then iterates through each character (`digit_char`) in the `num_str`.
    *   Each `digit_char` is converted back to an integer (`digit`).
    *   This `digit` is then raised to the power of `num_digits` (the total count of digits in the original number).
    *   The result is added to `sum_of_powers`.

5.  **Compare and Return**: After iterating through all digits, the `sum_of_powers` is compared with the original `number`.
    *   If they are equal, the function returns `True`, indicating it's an Armstrong number.
    *   Otherwise, it returns `False`.

## Explain Armstrong Number Logic

### Subtask:
Provide a brief explanation of how the generated Armstrong number checker function works.


The `is_armstrong_number` function determines if a given integer is an Armstrong number. Here's a breakdown of its logic:

1.  **Input Validation**: It first checks if the input `number` is an integer and non-negative. Armstrong numbers are typically defined for positive integers, so negative inputs are immediately deemed `False`.
2.  **Convert to String**: The `number` is converted to a string (`num_str`). This is essential to easily determine the number of digits and to iterate through each digit.
3.  **Count Digits**: The `len(num_str)` gives `num_digits`, which is the power to which each digit will be raised.
4.  **Calculate Sum of Powers**: The function initializes `sum_of_powers` to 0. It then iterates through each character (`digit_char`) in the `num_str`:
    *   Each `digit_char` is converted back to an integer (`digit`).
    *   This `digit` is raised to the power of `num_digits`.
    *   The result is added to `sum_of_powers`.
5.  **Comparison**: Finally, the calculated `sum_of_powers` is compared with the original `number`. If they are equal, the function returns `True`, indicating it's an Armstrong number; otherwise, it returns `False`.

## Prepare for Comparison

### Subtask:
Outline the steps for the user to generate an Armstrong number checker using GitHub Copilot and how we will perform a side-by-side comparison, including prompts and code.


## Prepare for Comparison

### Subtask:
Outline the steps for the user to generate an Armstrong number checker using GitHub Copilot and how we will perform a side-by-side comparison, including prompts and code.

#### Instructions
1.  **Generate a Python function using GitHub Copilot:** Open a new Python code cell in Google Colab. In this cell, write a prompt to GitHub Copilot asking it to generate a Python function that checks if a number is an Armstrong number. A suggested prompt is: `# Python function to check if a number is an Armstrong number`. Allow Copilot to complete the function.
2.  **Capture Copilot's output:** Take a screenshot of the prompt you used and the Python function that GitHub Copilot generated. Ensure the screenshot clearly shows both the prompt and the full function definition, including any docstrings or example usage provided by Copilot.
3.  **Prepare for comparison:** Once you have the screenshot, we will use it in the next step to create a side-by-side comparison with the function generated by Gemini (me).

## Final Task

### Subtask:
Create a side-by-side comparison table analyzing the outputs from Gemini and GitHub Copilot for the Armstrong number checker.


## Summary:

### Data Analysis Key Findings

*   The `is_armstrong_number` Python function, generated by Gemini, accurately determines if a given integer is an Armstrong number.
*   The function correctly identified known Armstrong numbers (e.g., 9, 153, 370, 371, 1634) and non-Armstrong numbers (e.g., 10, 1000).
*   It includes input validation to ensure the number is a non-negative integer, returning `False` for invalid inputs such as negative numbers (-153).
*   The logic involves converting the number to a string to count its digits, iterating through each digit, raising each digit to the power of the total number of digits, summing these results, and finally comparing this sum to the original number.
*   Detailed explanations were provided for the function's logic, breaking down steps like input validation, string conversion, digit counting, sum of powers calculation, and final comparison.
*   A clear outline was established for the user to generate an Armstrong number checker using GitHub Copilot and prepare for a side-by-side comparison, including a suggested prompt and instructions for capturing the output.

### Insights or Next Steps

*   Proceed with generating the Armstrong number checker using GitHub Copilot as outlined, capturing its output for a comprehensive comparison.
*   Conduct a side-by-side analysis of the functions generated by Gemini and GitHub Copilot to evaluate their approaches, efficiency, readability, and adherence to best practices.


**USING CURSOR AI**

In [4]:
"""
Task 3: Leap Year Validation Using Cursor AI

This file contains two different implementations of leap year validation,
demonstrating different coding approaches and styles.
"""

# ============================================================================
# VERSION 1: Explicit Step-by-Step Approach
# Prompt used: "Create a Python function that checks if a year is a leap year
#              using clear, step-by-step logic with detailed comments"
# ============================================================================

def is_leap_year_v1(year):
    """
    Check if a given year is a leap year using explicit step-by-step logic.

    Leap year rules:
    1. Divisible by 4 -> potential leap year
    2. But if divisible by 100 -> not a leap year (unless...)
    3. Unless also divisible by 400 -> then it IS a leap year

    Args:
        year (int): The year to check

    Returns:
        bool: True if leap year, False otherwise
    """
    # Step 1: Check if year is divisible by 4
    if year % 4 == 0:
        # Step 2: Check if year is divisible by 100
        if year % 100 == 0:
            # Step 3: Check if year is divisible by 400
            if year % 400 == 0:
                return True  # Divisible by 400 -> leap year
            else:
                return False  # Divisible by 100 but not 400 -> not leap year
        else:
            return True  # Divisible by 4 but not 100 -> leap year
    else:
        return False  # Not divisible by 4 -> not leap year


# ============================================================================
# VERSION 2: Concise Boolean Logic Approach
# Prompt used: "Write a Python function to determine leap years using
#              minimal code with boolean logic and short-circuit evaluation"
# ============================================================================

def is_leap_year_v2(year):
    """
    Check if a given year is a leap year using concise boolean logic.

    Logic: (divisible by 4) AND (not divisible by 100 OR divisible by 400)

    Args:
        year (int): The year to check

    Returns:
        bool: True if leap year, False otherwise
    """
    return (year % 4 == 0) and (year % 100 != 0 or year % 400 == 0)


# ============================================================================
# TESTING AND SAMPLE OUTPUTS
# ============================================================================

def test_leap_year_functions():
    """Test both versions with various sample inputs."""

    # Test cases: (year, expected_result, description)
    test_cases = [
        (2000, True, "Year 2000 - divisible by 400 (century leap year)"),
        (1900, False, "Year 1900 - divisible by 100 but not 400"),
        (2004, True, "Year 2004 - divisible by 4, not by 100"),
        (2024, True, "Year 2024 - divisible by 4, not by 100"),
        (2023, False, "Year 2023 - not divisible by 4"),
        (1600, True, "Year 1600 - divisible by 400"),
        (1700, False, "Year 1700 - divisible by 100 but not 400"),
        (1800, False, "Year 1800 - divisible by 100 but not 400"),
        (2008, True, "Year 2008 - divisible by 4, not by 100"),
        (2019, False, "Year 2019 - not divisible by 4"),
        (2400, True, "Year 2400 - divisible by 400"),
        (2100, False, "Year 2100 - divisible by 100 but not 400"),
    ]

    print("=" * 70)
    print("LEAP YEAR VALIDATION TEST RESULTS")
    print("=" * 70)
    print()

    all_passed = True

    for year, expected, description in test_cases:
        result_v1 = is_leap_year_v1(year)
        result_v2 = is_leap_year_v2(year)

        # Check if both versions agree
        if result_v1 != result_v2:
            print(f"❌ ERROR: Versions disagree for year {year}!")
            print(f"   V1: {result_v1}, V2: {result_v2}")
            all_passed = False
            continue

        # Check if result matches expected
        status = "✅ PASS" if result_v1 == expected else "❌ FAIL"
        if result_v1 != expected:
            all_passed = False

        print(f"{status} | Year: {year:4d} | Result: {str(result_v1):5s} | {description}")

    print()
    print("=" * 70)
    if all_passed:
        print("✅ All tests passed! Both versions produce correct results.")
    else:
        print("❌ Some tests failed. Please review the results above.")
    print("=" * 70)
    print()

    return all_passed


# ============================================================================
# COMPARISON OF VERSIONS
# ============================================================================

def print_comparison():
    """Print a brief comparison of the two versions."""

    print("=" * 70)
    print("BRIEF COMPARISON OF VERSION 1 vs VERSION 2")
    print("=" * 70)
    print()

    comparison = {
        "Version 1 (Explicit Step-by-Step)": {
            "Lines of Code": "~15 lines",
            "Readability": "⭐⭐⭐⭐⭐ Very high - clear nested if-else structure",
            "Maintainability": "⭐⭐⭐⭐⭐ Easy to understand and modify",
            "Performance": "⭐⭐⭐⭐ Similar performance",
            "Best For": "Beginners, educational purposes, when clarity is priority",
            "Code Style": "Imperative, explicit conditional checks"
        },
        "Version 2 (Concise Boolean Logic)": {
            "Lines of Code": "~1 line (single return statement)",
            "Readability": "⭐⭐⭐⭐ High - requires understanding of boolean logic",
            "Maintainability": "⭐⭐⭐⭐ Good - compact but may need comments",
            "Performance": "⭐⭐⭐⭐ Similar performance",
            "Best For": "Experienced developers, code golf, production code",
            "Code Style": "Functional, declarative, boolean expression"
        }
    }

    for version, attributes in comparison.items():
        print(f"{version}:")
        print("-" * 70)
        for key, value in attributes.items():
            print(f"  • {key:20s}: {value}")
        print()

    print("=" * 70)
    print("KEY DIFFERENCES:")
    print("=" * 70)
    print("1. VERSION 1 uses nested if-else statements for explicit logic flow")
    print("2. VERSION 2 uses a single boolean expression with AND/OR operators")
    print("3. Both produce identical results for all valid inputs")
    print("4. VERSION 1 is more verbose but easier to understand for beginners")
    print("5. VERSION 2 is more concise and follows Pythonic style")
    print("=" * 70)
    print()


# ============================================================================
# MAIN EXECUTION
# ============================================================================

if __name__ == "__main__":
    # Run tests
    test_leap_year_functions()

    # Print comparison
    print_comparison()

    # Interactive mode
    print("=" * 70)
    print("INTERACTIVE MODE")
    print("=" * 70)
    print("Enter a year to check (or 'quit' to exit):")
    print()

    while True:
        try:
            user_input = input("Year: ").strip()

            if user_input.lower() in ['quit', 'exit', 'q']:
                print("Goodbye!")
                break

            year = int(user_input)

            result_v1 = is_leap_year_v1(year)
            result_v2 = is_leap_year_v2(year)

            print(f"  Version 1 result: {result_v1}")
            print(f"  Version 2 result: {result_v2}")
            print(f"  {'✅ Leap Year!' if result_v1 else '❌ Not a Leap Year'}")
            print()

        except ValueError:
            print("  ❌ Please enter a valid integer year.")
            print()
        except KeyboardInterrupt:
            print("\nGoodbye!")
            break


LEAP YEAR VALIDATION TEST RESULTS

✅ PASS | Year: 2000 | Result: True  | Year 2000 - divisible by 400 (century leap year)
✅ PASS | Year: 1900 | Result: False | Year 1900 - divisible by 100 but not 400
✅ PASS | Year: 2004 | Result: True  | Year 2004 - divisible by 4, not by 100
✅ PASS | Year: 2024 | Result: True  | Year 2024 - divisible by 4, not by 100
✅ PASS | Year: 2023 | Result: False | Year 2023 - not divisible by 4
✅ PASS | Year: 1600 | Result: True  | Year 1600 - divisible by 400
✅ PASS | Year: 1700 | Result: False | Year 1700 - divisible by 100 but not 400
✅ PASS | Year: 1800 | Result: False | Year 1800 - divisible by 100 but not 400
✅ PASS | Year: 2008 | Result: True  | Year 2008 - divisible by 4, not by 100
✅ PASS | Year: 2019 | Result: False | Year 2019 - not divisible by 4
✅ PASS | Year: 2400 | Result: True  | Year 2400 - divisible by 400
✅ PASS | Year: 2100 | Result: False | Year 2100 - divisible by 100 but not 400

✅ All tests passed! Both versions produce correct results.

In [5]:
#original code
nums = (1, 2, 3, 4, 5, 6, 7)

even_sum = 0
odd_sum = 0

for n in nums:
    if n % 2 == 0:
        even_sum = even_sum + n
    else:
        odd_sum = odd_sum + n

print("Sum of even numbers:", even_sum)
print("Sum of odd numbers:", odd_sum)

#refactored code
nums = (1, 2, 3, 4, 5, 6, 7)

even_sum = sum(n for n in nums if n % 2 == 0)
odd_sum = sum(n for n in nums if n % 2 != 0)

print(f"Sum of even numbers: {even_sum}")
print(f"Sum of odd numbers: {odd_sum}")


Sum of even numbers: 12
Sum of odd numbers: 16
Sum of even numbers: 12
Sum of odd numbers: 16
